'use server';
import { getDb } from '@/lib/db'; import { audit, requireUser } from '@/lib/auth'; import { randomUUID } from 'crypto'; import { revalidatePath } from 'next/cache';
import { getCloudflareContext } from '@opennextjs/cloudflare';
export type ActionResult={ok:boolean;error?:string;duplicate?:boolean;fieldErrors?:Record<string,string>};
const cents=(v:FormDataEntryValue|null)=>Math.round(Number(v||0)*100);
export async function saveExpense(_:ActionResult|null,fd:FormData):Promise<ActionResult>{
 const user=await requireUser(['ADMIN','FINANCE']); const supplier=String(fd.get('supplier')||'').trim(); const total=cents(fd.get('total')); const vatRate=Number(fd.get('vatRate')||0);
 const fieldErrors:Record<string,string>={}; if(!supplier)fieldErrors.supplier='Supplier is required.'; if(!Number.isInteger(total)||total<=0)fieldErrors.total='Enter an amount greater than zero.';
 const date=String(fd.get('transactionDate')||''); if(!/^\d{4}-\d{2}-\d{2}$/.test(date))fieldErrors.transactionDate='Choose a valid date.'; if(Object.keys(fieldErrors).length)return{ok:false,fieldErrors};
 const db=await getDb(); const duplicate=await db.prepare("SELECT id FROM expenses WHERE supplier=? AND transaction_date=? AND total_cents=? AND status!='VOID' LIMIT 1").bind(supplier,date,total).first();
 if(duplicate&&fd.get('confirmDuplicate')!=='yes')return{ok:false,duplicate:true,error:'A matching expense already exists. Confirm to save another.'};
 const vat=Math.round(total*vatRate/(100+vatRate)); const ex=total-vat; const id=String(fd.get('id')||randomUUID()); const category=String(fd.get('categoryId')||'')||null; const lead=String(fd.get('leadId')||'')||null; const status=String(fd.get('status'))==='POSTED'?'POSTED':'DRAFT';
 const exists=await db.prepare('SELECT id FROM expenses WHERE id=?').bind(id).first();
 if(exists) await db.prepare(`UPDATE expenses SET supplier=?,description=?,transaction_date=?,category_id=?,reference=?,amount_ex_vat_cents=?,vat_cents=?,vat_rate=?,total_cents=?,payment_method=?,notes=?,lead_id=?,allocation_type=?,status=?,updated_at=datetime('now') WHERE id=? AND status!='VOID'`)
  .bind(supplier,String(fd.get('description')||''),date,category,String(fd.get('reference')||''),ex,vat,vatRate,total,String(fd.get('paymentMethod')||''),String(fd.get('notes')||''),lead,lead?'PROJECT':'OVERHEAD',status,id).run();
 else await db.prepare(`INSERT INTO expenses(id,supplier,description,transaction_date,category_id,reference,amount_ex_vat_cents,vat_cents,vat_rate,total_cents,payment_method,notes,lead_id,allocation_type,status,source,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'MANUAL',?)`)
  .bind(id,supplier,String(fd.get('description')||''),date,category,String(fd.get('reference')||''),ex,vat,vatRate,total,String(fd.get('paymentMethod')||''),String(fd.get('notes')||''),lead,lead?'PROJECT':'OVERHEAD',status,user.id).run();
 await audit(exists?'EXPENSE_UPDATED':'EXPENSE_CREATED','expense',id,{status}); revalidatePath('/'); return{ok:true};
}
export async function voidExpense(id:string,reason:string){const user=await requireUser(['ADMIN','FINANCE']);if(!reason.trim())throw new Error('A void reason is required');await(await getDb()).prepare("UPDATE expenses SET status='VOID',voided_at=datetime('now'),void_reason=?,updated_at=datetime('now') WHERE id=?").bind(reason,id).run();await audit('EXPENSE_VOIDED','expense',id,{reason,user:user.id});revalidatePath('/');}
export async function uploadReceipt(fd:FormData){await requireUser(['ADMIN','FINANCE']);const id=String(fd.get('expenseId')),file=fd.get('file');if(!(file instanceof File)||file.size===0||file.size>10_000_000)throw new Error('Choose a receipt under 10 MB');if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Only PDF, JPG, PNG, or WebP receipts are supported');const key=`expenses/${id}/${randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {env}=await getCloudflareContext({async:true});await env.PRIVATE_FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});await(await getDb()).prepare("UPDATE expenses SET receipt_key=?,updated_at=datetime('now') WHERE id=?").bind(key,id).run();await audit('EXPENSE_RECEIPT_UPLOADED','expense',id,{key});revalidatePath('/');}
export async function getExpenseData(filters?:{q?:string;status?:string;from?:string;to?:string}){await requireUser(['ADMIN','FINANCE']);const db=await getDb();const cats=(await db.prepare('SELECT * FROM expense_categories WHERE active=1 ORDER BY name').all()).results??[];const leads=(await db.prepare("SELECT id,project,company FROM leads ORDER BY created_at DESC LIMIT 200").all()).results??[];let sql=`SELECT e.*,c.name category_name,l.project project_name FROM expenses e LEFT JOIN expense_categories c ON c.id=e.category_id LEFT JOIN leads l ON l.id=e.lead_id WHERE 1=1`;const args:unknown[]=[];if(filters?.q){sql+=' AND (e.supplier LIKE ? OR e.description LIKE ? OR e.reference LIKE ?)';args.push(...Array(3).fill(`%${filters.q}%`));}if(filters?.status){sql+=' AND e.status=?';args.push(filters.status);}if(filters?.from){sql+=' AND e.transaction_date>=?';args.push(filters.from);}if(filters?.to){sql+=' AND e.transaction_date<=?';args.push(filters.to);}sql+=' ORDER BY e.transaction_date DESC,e.created_at DESC';const expenses=(await db.prepare(sql).bind(...args).all()).results??[];return{expenses,categories:cats,leads};}
